name: PUSHCI

on: [push]

jobs:
  unit_tests:
      name: unit tests
      runs-on: ubuntu-latest
      steps:
        - name: checkout code
          uses: actions/checkout@v1
        - name: set up node ${{ matrix.node-version }}
          uses: actions/setup-node@v1
          with:
            node-version: 12.16.2
            registry-url: https://npm.pkg.github.com/
            scope: "@wh-iterabb-it"
        - name: install dependencies
          working-directory: .
          run: npm ci
          env:
            NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}
        - name: docker build
          run: docker build -t wh-iterabb-it/aphorismcookie .
          env:
            NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}
        - name: create container env
          run: docker-compose up -d
        - name: running npm test
          run: docker run wh-iterabb-it/aphorismcookie npm run test
        - name: running npm cover
          run: docker run wh-iterabb-it/aphorismcookie npm run cover
        - uses: codecov/codecov-action@v1
          with:
            token: ${{ secrets.CODECOV_TOKEN }}
            file: ./coverage.txt
